# CROSS FLODING

In [190]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn. ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score,KFold
from sklearn.model_selection import train_test_split

In [191]:
df=pd.read_csv('/kaggle/input/iris-dataset1/iris.csv')

In [192]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [193]:
x=df.drop(['species'],axis=1)

In [194]:
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [195]:
y=df['species']

In [196]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [197]:
x_train.head()

sepal_length  sepal_width  petal_length  petal_width
22           4.6          3.6           1.0          0.2
15           5.7          4.4           1.5          0.4
65           6.7          3.1           4.4          1.4
11           4.8          3.4           1.6          0.2
42           4.4          3.2           1.3          0.2

In [198]:
y_train.head()

22        setosa
15        setosa
65    versicolor
11        setosa
42        setosa
Name: species, dtype: object

In [199]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

1.0

In [200]:
kf=KFold(n_splits=3)

In [201]:
w=[11,21,31,41,15,16,71,18,91]
for p,q in kf.split(w):
    print(p,q) #index print 

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [202]:
a=[]
an=[]

In [203]:
lx = cross_val_score(LogisticRegression(max_iter=1000), x, y, cv=3)


In [204]:
lx

array([0.98, 0.96, 0.98])

In [205]:
z=np.average(lx)


In [206]:
z

0.9733333333333333

In [207]:
a.append(z)
an.append('LR')

In [208]:
a

[0.9733333333333333]

In [209]:
an

['LR']

In [210]:
dx=cross_val_score(DecisionTreeClassifier(),x,y,cv=3)

In [211]:
dx

array([0.98, 0.94, 0.98])

In [212]:
z=np.average(dx)
a.append(z)
an.append('Dr')

In [213]:
a

[0.9733333333333333, 0.9666666666666667]

In [214]:
an

['LR', 'Dr']

In [215]:
rf=cross_val_score(RandomForestClassifier(),x,y,cv=3)

In [216]:
rf

array([0.98, 0.92, 0.98])

In [217]:
z=np.average(rf)
a.append(z)
an.append('RF')

In [218]:
a

[0.9733333333333333, 0.9666666666666667, 0.96]

In [219]:
an

['LR', 'Dr', 'RF']

In [220]:
sx=cross_val_score(SVC(),x,y,cv=3)

In [221]:
z=np.average(sx)
a.append(z)
an.append('SV')

In [222]:
np.max(a)

0.9733333333333333

In [223]:
a

[0.9733333333333333, 0.9666666666666667, 0.96, 0.96]

In [224]:
an

['LR', 'Dr', 'RF', 'SV']

In [225]:
an[np.argmax(a)]

'LR'